name: First Github Actions setup

on:
  push:
    branches: ['main']

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Run app
        run: node index.js